---
title: "BubbleTree_Shannon_Wu"
output: html_document
date: "2025-02-24"
---

```{r setup, include=FALSE}
knitr::knit_global()
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r load_libraries, include=FALSE}
# Load required packages
#BiocManager::install("scBubbletree")
library(scBubbletree)
library(ggplot2)
library(ggtree)
library(patchwork)
#BiocManager::install("glmGamPoi")
# install sctransform from Github
#install.packages("sctransform")
library(Seurat)
library(patchwork)
library(dplyr)
library(ggplot2)
library(sctransform)
library(ggpmisc)
library(caret)
library(ggpubr)
library(multcomp)

options(future.globals.maxSize = 10 * 1024^4)

setwd("D:/Dropbox/Master Thesis/Methods_transcript/Biodiversity/BubbleTree/Wu/1%threshold")

```

```{r load_datasets, include=FALSE}
# load datasets
setwd("D:/Dropbox/Master Thesis/Datasets/Wu/Data_Wu2021_Breast")
Seu_Wu_Breast <- readRDS("D:/Dropbox/Master Thesis/Datasets/Wu/Data_Wu2021_Breast/Seu_Wu_Breast.rds")

# QC
# filter
Seu_Wu_Breast <- subset(Seu_Wu_Breast, subset = nFeature_RNA > 250)

### Subset normals
Seu_Wu_Normals <- subset(Seu_Wu_Breast, subset = cell_type == "Epithelial")
table(Seu_Wu_Normals@meta.data[["cell_subtype"]], Seu_Wu_Normals@meta.data[["patient"]])
Seu_Wu_Normals <- subset(Seu_Wu_Normals, subset = patient != "CID4530N") #remove CID4530N, only 46 cells

Seu_Wu_N_B <- subset(Seu_Wu_Normals, subset = cell_subtype == "Myoepithelial")
Seu_Wu_N_LP <- subset(Seu_Wu_Normals, subset = cell_subtype == "Luminal Progenitors")
Seu_Wu_N_HR <- subset(Seu_Wu_Normals, subset = cell_subtype == "Mature Luminal")

### subset tumors
Seu_Wu_Tumors <- subset(Seu_Wu_Breast, subset = cell_type == "Malignant")
table(Seu_Wu_Tumors@meta.data[["disease"]], Seu_Wu_Tumors@meta.data[["patient"]])

Seu_Wu_ER <- subset(Seu_Wu_Tumors, subset = disease == "ER+")
Seu_Wu_HER2 <- subset(Seu_Wu_Tumors, subset = disease == "HER2+")
Seu_Wu_TNBC<- subset(Seu_Wu_Tumors, subset = disease == "TNBC")


```

```{r functions}
select_dims <- function(object) {
  pct <- object[["pca"]]@stdev / sum(object[["pca"]]@stdev) * 100
  PCopt <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1
  return(1:PCopt)
}

scBubblePlotPipeline <- function(d){
  # Select the 5,000 most variable genes
  d <- FindVariableFeatures(object = d, selection.method = "vst", nfeatures = 5000)
  # Normalize the data using SCTransform
  d <- SCTransform(d, variable.features.n = 5000)
  # Run PCA
  d <- RunPCA(object = d, npcs = 50, features = VariableFeatures(object = d))
  # select optimal dims
  selected_dims <- select_dims(d)
  
  ### scBubbleTree
    # Extract the PCA embeddings
    A <- d@reductions$pca@cell.embeddings[, 1:length(selected_dims)]
    m <- d@meta.data
    d_ccl <- list(A = A, m = m)
    
    #k-means
    b_k <- get_k(B_gap = 10,
             ks = 1:30, # no. of ks
             x = A, # input matrix
             n_start = 50, 
             iter_max = 100,
             kmeans_algorithm = "MacQueen", 
             cores = 2)
    
    ## find optimal k
    gap_stats <- b_k$gap_stats_summary
    gap_diff <- diff(gap_stats$gap_mean) / gap_stats$gap_mean[-length(gap_stats$gap_mean)]
    optimal_k <- which(gap_diff < 0.01)[1] # First k where % change < 1%
    
    k <- get_bubbletree_kmeans(x = A,
                           k = optimal_k,
                           cores = 1,
                           B = 300,
                           N_eff = 200,
                           round_digits = 1,
                           show_simple_count = FALSE,
                           kmeans_algorithm = "MacQueen")
    return(k)
}


CalcShannonEntropy <- function(trees_list){
  # Initialize Shannon entropy list
  Shannon_list <- c()

  # Loop through the list of trees
  for (i in seq_along(trees_list)) {
    # Extract the current tree
    tree <- trees_list[[i]]

    # Check if "tree_meta" exists in the current tree
    if ("tree_meta" %in% names(tree)) {
      # Extract tree metadata
      results_df <- tree[["tree_meta"]]

      # Calculate Shannon entropy
      probs <- results_df$p
      Shannon_list[i] <- -sum(probs * log2(probs), na.rm = TRUE)
    } else {
      # Assign 0 if "tree_meta" is not present
      Shannon_list[i] <- 0
    }
  }
   return(Shannon_list)
}
```

```{r BubbleTree}
### Normal ------------------------------------------
# get IDs
normal_ID <- as.character(unique(Seu_Wu_Normals@meta.data$patient))
# Split so by patient
Seu_Wu_Normals_split <- SplitObject(Seu_Wu_Normals, split.by = "patient")

### Biodiversity - Shannon Entropy
# 1. Run scBubbleTree pipeline (k-means, with threshold of 1%)
  # create list to store trees after scBubbleTree pipeline
  trees_list <- vector("list", length = length(normal_ID))
  
  # Run scBubbleTree for each patient
  for (i in 1:length(Seu_Wu_Normals_split)) {
    # split patients
    patient <- Seu_Wu_Normals_split[[i]]
    # run scBubbleTree pipeline
    trees_list[[i]] <- tryCatch(
    scBubblePlotPipeline(patient),
    error = function(e) if (grepl("k must be a positive integer", e$message)) 0 else stop(e)
  )
}
  # save
  Wu_Normal_Trees_List <- trees_list
  names(Wu_Normal_Trees_List) <- normal_ID
  save(Wu_Normal_Trees_List, file = "Wu_Normal_Trees_List.RData")


### Normal B ------------------------------------------
# get IDs
normal_ID <- as.character(unique(Seu_Wu_N_B@meta.data$patient))
# Split so by patient
Seu_Wu_N_Bsplit <- SplitObject(Seu_Wu_N_B, split.by = "patient")

### Biodiversity - Shannon Entropy
# 1. Run scBubbleTree pipeline (k-means, with threshold of 1%)
  # create list to store trees after scBubbleTree pipeline
  trees_list <- vector("list", length = length(normal_ID))
  
  # Run scBubbleTree for each patient
  for (i in 1:length(Seu_Wu_N_Bsplit)) {
    # split patients
    patient <- Seu_Wu_N_Bsplit[[i]]
    # run scBubbleTree pipeline
    trees_list[[i]] <- tryCatch(
    scBubblePlotPipeline(patient),
    error = function(e) if (grepl("k must be a positive integer", e$message)) 0 else stop(e)
  )
}
  # save
  Wu_Normal_B_Trees_List <- trees_list
  Wu_Normal_B_Trees_List <- lapply(Wu_Normal_B_Trees_List, function(x) if (is.null(x)) 0 else x)
  names(Wu_Normal_B_Trees_List) <- normal_ID
  save(Wu_Normal_B_Trees_List, file = "Wu_Normal_B_Trees_List.RData")

  
  
### Normal LP ------------------------------------------
# get IDs
normal_ID <- as.character(unique(Seu_Wu_N_LP@meta.data$patient))
# Split so by patient
Seu_Wu_N_LP_split <- SplitObject(Seu_Wu_N_LP, split.by = "patient")

### Biodiversity - Shannon Entropy
# 1. Run scBubbleTree pipeline (k-means, with threshold of 1%)
  # create list to store trees after scBubbleTree pipeline
  trees_list <- vector("list", length = length(normal_ID))
  
  # Run scBubbleTree for each patient
  for (i in 1:length(Seu_Wu_N_LP_split)) {
    # split patients
    patient <- Seu_Wu_N_LP_split[[i]]
    # run scBubbleTree pipeline
    trees_list[[i]] <- tryCatch(
    scBubblePlotPipeline(patient),
    error = function(e) if (grepl("k must be a positive integer", e$message)) 0 else stop(e)
  )
}
  # save
  Wu_Normal_LP_Trees_List <- trees_list
  Wu_Normal_LP_Trees_List <- lapply(Wu_Normal_LP_Trees_List, function(x) if (is.null(x)) 0 else x)
  names(Wu_Normal_LP_Trees_List) <- normal_ID
  save(Wu_Normal_LP_Trees_List, file = "Wu_Normal_LP_Trees_List.RData")
  
  
  
### Normal HR ------------------------------------------
# get IDs
normal_ID <- as.character(unique(Seu_Wu_N_HR@meta.data$patient))
# Split so by patient
Seu_Wu_N_HR_split <- SplitObject(Seu_Wu_N_HR, split.by = "patient")

### Biodiversity - Shannon Entropy
# 1. Run scBubbleTree pipeline (k-means, with threshold of 1%)
  # create list to store trees after scBubbleTree pipeline
  trees_list <- vector("list", length = length(normal_ID))
  
  # Run scBubbleTree for each patient
  for (i in 1:length(Seu_Wu_N_HR_split)) {
    # split patients
    patient <- Seu_Wu_N_HR_split[[i]]
    # run scBubbleTree pipeline
    trees_list[[i]] <- tryCatch(
    scBubblePlotPipeline(patient),
    error = function(e) if (grepl("k must be a positive integer", e$message)) 0 else stop(e)
  )
}
  # save
  Wu_Normal_HR_Trees_List <- trees_list
  Wu_Normal_HR_Trees_List <- lapply(Wu_Normal_HR_Trees_List, function(x) if (is.null(x)) 0 else x)
  names(Wu_Normal_HR_Trees_List) <- normal_ID
  save(Wu_Normal_HR_Trees_List, file = "Wu_Normal_HR_Trees_List.RData")
  
  

### Tumor ------------------------------------------
# get IDs
tumor_id <- as.character(unique(Seu_Wu_Tumors@meta.data$patient))
# Split so by patient
Seu_Wu_Tumors_split <- SplitObject(Seu_Wu_Tumors, split.by = "patient")

### Biodiversity - Shannon Entropy
# 1. Run scBubbleTree pipeline (k-means, with threshold of 1%)
  # create list to store trees after scBubbleTree pipeline
  trees_list <- vector("list", length = length(tumor_id))
  
  # Run scBubbleTree for each patient
  for (i in 1:length(Seu_Wu_Tumors_split)) {
    # split patients
    patient <- Seu_Wu_Tumors_split[[i]]
    # run scBubbleTree pipeline
    trees_list[[i]] <- tryCatch(
    scBubblePlotPipeline(patient),
    error = function(e) if (grepl("k must be a positive integer", e$message)) 0 else stop(e)
  )
}
  # save
  Wu_Tumours_Trees_List <- trees_list
  Wu_Tumours_Trees_List <- lapply(Wu_Tumours_Trees_List, function(x) if (is.null(x)) 0 else x)
  names(Wu_Tumours_Trees_List) <- tumor_id
  save(Wu_Tumours_Trees_List, file = "Wu_Tumours_Trees_List.RData")
  
```

```{r visualization_NvsNs}
# load
load("D:/Dropbox/Master Thesis/Methods_transcript/Biodiversity/BubbleTree/Wu/Wu_Normal_Trees_List.RData")
load("D:/Dropbox/Master Thesis/Methods_transcript/Biodiversity/BubbleTree/Wu/Wu_Normal_B_Trees_List.RData")
load("D:/Dropbox/Master Thesis/Methods_transcript/Biodiversity/BubbleTree/Wu/Wu_Normal_LP_Trees_List.RData")
load("D:/Dropbox/Master Thesis/Methods_transcript/Biodiversity/BubbleTree/Wu/Wu_Normal_HR_Trees_List.RData")

normal_ID <- names(Wu_Normal_Trees_List)

# 2. Calculate Shannon-Entropy from proportions
Normal_Shannon_df <- CalcShannonEntropy(Wu_Normal_Trees_List)
Normal_Shannon_df <- data.frame(SE = Normal_Shannon_df,
                                patient = normal_ID,
                                group = rep("All Epi", times = length(Normal_Shannon_df)))

Normal_Shannon_B_df <- CalcShannonEntropy(Wu_Normal_B_Trees_List)
Normal_Shannon_B_df <- data.frame(SE = Normal_Shannon_B_df,
                                patient = normal_ID,
                                group = rep("Basal", times = length(Normal_Shannon_B_df)))

Normal_Shannon_LP_df <- CalcShannonEntropy(Wu_Normal_LP_Trees_List)
Normal_Shannon_LP_df <- data.frame(SE = Normal_Shannon_LP_df,
                                patient = normal_ID,
                                group = rep("LP", times = length(Normal_Shannon_LP_df)))

Normal_Shannon_HR_df <- CalcShannonEntropy(Wu_Normal_HR_Trees_List)
Normal_Shannon_HR_df <- data.frame(SE = Normal_Shannon_HR_df,
                                patient = normal_ID,
                                group = rep("HR", times = length(Normal_Shannon_HR_df)))

Shannon_all_df <- rbind(Normal_Shannon_df, Normal_Shannon_B_df, Normal_Shannon_LP_df, Normal_Shannon_HR_df)


ggplot(Shannon_all_df, aes(x = group, y = SE, fill = group)) +
  geom_boxplot(outlier.shape = NA) +  # Boxplot without outliers
  geom_jitter(width = 0.2, size = 2, color = "black") +  # Jittered points with black color
  scale_fill_manual(values = c("#5c8d92", "#b8d7ac", "#a3cdc7", "#97b5c3")) +  # Custom palette
  labs(
    x = "Group",
    y = "Shannon Entropy",
    fill = "Group"
  ) +
  theme_minimal() +
  theme(
    legend.position = "right",
    plot.title = element_text(hjust = 0.5, face = "bold")
  )



### Statistical test
# Check normality
shapiro.test(Shannon_all_df$SE[Shannon_all_df$group == "All Epi"])
shapiro.test(Shannon_all_df$SE[Shannon_all_df$group == "Basal"]) 
shapiro.test(Shannon_all_df$SE[Shannon_all_df$group == "LP"]) #-> not normal
shapiro.test(Shannon_all_df$SE[Shannon_all_df$group == "HR"])

### Kruskal-Wallis with Dunns post hoc test for multiple comparisons
Shannon_all_df$group <- factor(Shannon_all_df$group)
Shannon_all_df$group <- relevel(Shannon_all_df$group, ref = "All Epi") # set All Epi as reference group

kruskal_result <- kruskal.test(SE ~ group, data = Shannon_all_df)
dunn_test <- dunn_test(SE ~ group, data = Shannon_all_df, p.adjust.method = "bonferroni")
summary(dunn_test)
pvalues <- as.vector(dunn_test$p.adj)
pvalues <- pvalues[c(1,3,2)] # order



### Plots with significance labels 
sig_df <- data.frame(
  group1 = c("All Epi", "All Epi", "All Epi"),
  group2 = c("Basal", "LP", "HR"),
  y.position = c(3.8, 4.2, 4.6),  # change these values as needed
  p.adj = pvalues
)

# convert p-values to star labels
sig_df$label <- ifelse(sig_df$p.adj < 0.001, "***", 
                  ifelse(sig_df$p.adj < 0.01, "**",
                  ifelse(sig_df$p.adj < 0.05, "*", "ns")))

Shannon_all_df <- Shannon_all_df %>% mutate(group = factor(group, levels = c("All Epi", "Basal", "LP", "HR")))

p <- ggboxplot(Shannon_all_df, x = "group", y = "SE",
          fill = "group", 
          palette = c("#5c8d92", "#b8d7ac", "#a3cdc7", "#97b5c3"),
          xlab = "Group",
          ylab = "Shannon Entropy",
          add = "jitter") +
  stat_pvalue_manual(sig_df, label = "label", tip.length = 0.01) +
  theme(legend.position = "none") +
  coord_cartesian(ylim = c(0, 5))

p



setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Real/Wu")
ggsave(filename = "Wu_SE_NvsN.tiff", plot = p, width = 4, height = 2.5, dpi = 1200)
```


```{r visualization_NvsT}
# load
load("D:/Dropbox/Master Thesis/Methods_transcript/Biodiversity/BubbleTree/Wu/Wu_Tumours_Trees_List.RData")

# do mean of subtypes:
Normal_mean_Shannon_df <- rbind(Normal_Shannon_B_df, Normal_Shannon_LP_df, Normal_Shannon_HR_df)
Normal_mean_Shannon_df <- aggregate(Normal_mean_Shannon_df[,1:2], list(Normal_mean_Shannon_df$patient), FUN=mean)
Normal_mean_Shannon_df <- Normal_mean_Shannon_df[,-1]
Normal_mean_Shannon_df$group <- rep("Mean Epi")

# 2. Calculate Shannon-Entropy from proportions
patient_ID <- names(Wu_Tumours_Trees_List)
Tumour_Shannon_df <- CalcShannonEntropy(Wu_Tumours_Trees_List)
Tumour_Shannon_df <- data.frame(SE = Tumour_Shannon_df,
                                patient = tumor_id,
                                group = rep("Breast Cancer", times = length(Tumour_Shannon_df)))


Shannon_Nmean_vs_T_df <- rbind(Normal_mean_Shannon_df, Tumour_Shannon_df)
Shannon_Nmean_vs_T_df <- Shannon_Nmean_vs_T_df %>% mutate(group = factor(group, levels = c("Mean Epi", "Breast Cancer")))

ggplot(Shannon_Nmean_vs_T_df, aes(x = group, y = SE, fill = group)) +
  geom_boxplot(outlier.shape = NA) +  # Boxplot without outliers
  geom_jitter(width = 0.2, size = 2, color = "black") +  # Jittered points with black color
  scale_fill_manual(values = c("#9dbebb", "#dd9a98")) +  # Custom palette
  labs(
    x = "Group",
    y = "Shannon Entropy",
    fill = "Group"
  ) +
  theme_minimal() +
  theme(
    legend.position = "right",
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Real/Wu")
ggsave(filename = "Wu_SE_NvsT.tiff", plot = p, width = 4, height = 2.5, dpi = 1200)



### Statistical test
# Check normality
shapiro.test(Shannon_Nmean_vs_T_df$SE[Shannon_Nmean_vs_T_df$group == "Mean Epi"]) #-> not normal
shapiro.test(Shannon_Nmean_vs_T_df$SE[Shannon_Nmean_vs_T_df$group == "Breast Cancer"]) 

# Mann Whitney U
mw_test <- wilcox.test(SE ~ group, data = Shannon_Nmean_vs_T_df, exact = FALSE)
pvalue <- mw_test$p.value

### Plots with significance labels 
sig_df <- data.frame(
  group1 = c("Mean Epi"),
  group2 = c("Breast Cancer"),
  y.position = c(4),  # change these values as needed
  p.adj = pvalue
)

# convert p-values to star labels
sig_df$label <- ifelse(sig_df$p.adj < 0.001, "***", 
                  ifelse(sig_df$p.adj < 0.01, "**",
                  ifelse(sig_df$p.adj < 0.05, "*",  round(pvalue, 3))))

Shannon_Nmean_vs_T_df <- Shannon_Nmean_vs_T_df %>% mutate(group = factor(group, levels = c("Mean Epi", "Breast Cancer")))

p <- ggboxplot(Shannon_Nmean_vs_T_df, x = "group", y = "SE",
          fill = "group", 
          palette = c("#9dbebb", "#dd9a98"),
          xlab = "Group",
          ylab = "Shannon Entropy",
          add = "jitter") +
  stat_pvalue_manual(sig_df, label = "label", tip.length = 0.01, size = 3) +
  theme(legend.position = "none") +
  coord_cartesian(ylim = c(0, 5))

p


setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Real/Wu")
ggsave(filename = "Wu_SE_NvsT_sig.tiff", plot = p, width = 3, height = 2.5, dpi = 1200)


```
