---
title: "Centroid_distance_Reed_optPC"
output: html_document
date: "2025-02-23"
---

```{r setup, include=FALSE}
knitr::knit_global()
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r load_libraries, include=FALSE}
# Load required package
library(Seurat)
library(ggplot2)
library(ggpmisc)
library(caret)
library(ggpubr)
library(multcomp)

# set seed
set.seed(43)


```

```{r load_datasets, include=FALSE}
# load datasets
load("D:/Dropbox/Master Thesis/Datasets/Reed/seu_reed_normal.RData")

```

```{r QC}
### Normal
# filter
seu_reed_normal <- subset(seu_reed_normal, subset = nFeaturess_RNA > 250)
table(seu_reed_normal@meta.data[["level1_global"]], seu_reed_normal@meta.data[["donor_id"]]) # remove patient: HBCA_Donor_20, HBCA_Donor_20

# remove bad patient
seu_reed_normal <- subset(seu_reed_normal, subset = donor_id != "HBCA_Donor_3")
seu_reed_normal <- subset(seu_reed_normal, subset = donor_id != "HBCA_Donor_20")
                          
# subset normal into 3 subpopulations
seu_reed_normal_B <- subset(seu_reed_normal, subset = level1_global == "Basal-myoepithelial")
seu_reed_normal_LP <- subset(seu_reed_normal, subset = level1_global == "Luminal adaptive secretory precurser")
seu_reed_normal_HR <- subset(seu_reed_normal, subset = level1_global == "Luminal hormone sensing")


```

```{r functions}
### Functions ###
## function: RunSeuratPipeline
RunSeuratPipeline <- function(seu_object){
  seu_object <- NormalizeData(seu_object, normalization.method = "LogNormalize", scale.factor = 10000)
  seu_object <- FindVariableFeatures(seu_object, selection.method = "vst", nfeatures = 2000)
  seu_object <- ScaleData(seu_object)
  seu_object <- RunPCA(seu_object)
  return(seu_object)
}

## function: extract PCs and SDs
# extract PCs
GetPCs <- function(seu_object){
  # get optimal PC
  pct <- seu_object[["pca"]]@stdev / sum(seu_object[["pca"]]@stdev) * 100
  cumu <- cumsum(pct)
  #co1 <- which(cumu > 50)[1]
  co2 <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1
  #pcs <- min(co1, co2)
  pcs <- co2
  PCs <- as.data.frame(seu_object@reductions$pca@cell.embeddings[,c(1:pcs)])
  return(PCs)
}

# extract SDs
GetSDs <- function(seu_object, numPC){
  pca <- seu_object@reductions$pca
  total_variance <- seu_object@reductions$pca@misc$total.variance
  eigValues <- (pca@stdev)^2
  varExplained <- eigValues / total_variance
  SDs <- (varExplained * 100)[1:numPC]
  return(SDs)
}
## function: calculate centroid distance
CalculateCentroidDistance <- function(PCs, withSD = NULL, SDs = NULL){
  centroid_list <- as.vector(apply(PCs, 2, mean)) # calculate centroid for all PCs
  centroid_matrix <- sweep(PCs, 2, centroid_list) # create matrix with centroid in the center (by substraction of centroid list)
  # Calculate distance
  if (!is.null(withSD)) {
    distance <- sqrt(rowSums((sweep(centroid_matrix, 2, SDs, "*"))^2)) # with SD correction (if)
  } else {
    distance <- sqrt(rowSums(centroid_matrix^2)) # normal
  }
  distance <- as.matrix(distance)
  return(distance)
}
```

Centroid distances of Normals with variance weighting and optimal PCs

```{r Normals_PC, fig.height=3, fig.width=5}

#  Optimal PCs with weighted variance
#### Cluster Analysis ####
### Normal ------------------------------------------
# get IDs
normal_ID <- as.character(unique(seu_reed_normal@meta.data$donor_id))
# Split so by patient
seu_reed_normal_split <- SplitObject(seu_reed_normal, split.by = "donor_id")

### Distance analysis
## get PCA coordinates
# initialize list to store df and SD for PCs
PCs <- vector("list", length = length(normal_ID)) # PCs
PC_SD <- vector("list", length = length(normal_ID)) # SD of PCs

# extract PCs and SDs per patient in for loop
for (i in 1:length(seu_reed_normal_split)) {
  # split patients
  patient <- seu_reed_normal_split[[i]]
    # seurat pipeline
    patient <- RunSeuratPipeline(patient)
    # get PCs and SDs
    PCs[[i]] <- GetPCs(patient)
    PC_SD[[i]] <- GetSDs(patient, length(PCs))
}
## calculate distance to centroid with SD correction
# calculate centroid
# initiate list
centroid_distances <- vector("list", length = length(PCs))
#
for (i in 1:length(PCs)) {
  centroid_distances[[i]] <- CalculateCentroidDistance(PCs[[i]], withSD = TRUE, PC_SD[[i]])
}

# summary
mean <- c()
sd <- c()

for (i in 1:length(centroid_distances)) {
  mean[i] <- mean(centroid_distances[[i]])
  sd[i] <- sd(centroid_distances[[i]])
}
#
#cell_count <- as.data.frame(table(seu_reed_normal@meta.data$donor_id))
centroid_sum_N <- data.frame(mean = mean, sd = sd, patient_id = normal_ID, group = c(rep("All Epi", times = length(centroid_distances))))


### Normal B ------------------------------------------
# get IDs
normal_ID <- as.character(unique(seu_reed_normal_B@meta.data$donor_id))
# Split so by patient
seu_reed_normal_B_split <- SplitObject(seu_reed_normal_B, split.by = "donor_id")

### Distance analysis
## get PCA coordinates
# initialize list to store df and SD for PCs
PCs <- vector("list", length = length(normal_ID)) # PCs
PC_SD <- vector("list", length = length(normal_ID)) # SD of PCs

# extract PCs and SDs per patient in for loop
for (i in 1:length(seu_reed_normal_B_split)) {
  # split patients
  patient <- seu_reed_normal_B_split[[i]]
    # seurat pipeline
    patient <- RunSeuratPipeline(patient)
    # get PCs and SDs
    PCs[[i]] <- GetPCs(patient)
    PC_SD[[i]] <- GetSDs(patient, length(PCs))
}
## calculate distance to centroid with SD correction
# calculate centroid
# initiate list
centroid_distances <- vector("list", length = length(PCs))
#
for (i in 1:length(PCs)) {
  centroid_distances[[i]] <- CalculateCentroidDistance(PCs[[i]], withSD = TRUE, PC_SD[[i]])
}

# summary
mean <- c()
sd <- c()

for (i in 1:length(centroid_distances)) {
  mean[i] <- mean(centroid_distances[[i]])
  sd[i] <- sd(centroid_distances[[i]])
}
#
#cell_count <- as.data.frame(table(seu_reed_normal_B@meta.data$donor_id))
centroid_sum_B <- data.frame(mean = mean, sd = sd, patient_id = normal_ID, group = c(rep("Basal", times = length(centroid_distances))))



### Normal LP ------
# get IDs
normal_ID <- as.character(unique(seu_reed_normal_LP@meta.data$donor_id))
# Split so by patient
seu_reed_normal_LP_split <- SplitObject(seu_reed_normal_LP, split.by = "donor_id")

### Distance analysis
## get PCA coordinates
# initialize list to store df and SD for PCs
PCs <- vector("list", length = length(normal_ID)) # PCs
PC_SD <- vector("list", length = length(normal_ID)) # SD of PCs

# extract PCs and SDs per patient in for loop
for (i in 1:length(seu_reed_normal_LP_split)) {
  # split patients
  patient <- seu_reed_normal_LP_split[[i]]
    # seurat pipeline
    patient <- RunSeuratPipeline(patient)
    # get PCs and SDs
    PCs[[i]] <- GetPCs(patient)
    PC_SD[[i]] <- GetSDs(patient, length(PCs))
}
## calculate distance to centroid with SD correction
# calculate centroid
# initiate list
centroid_distances <- vector("list", length = length(PCs))
#
for (i in 1:length(PCs)) {
  centroid_distances[[i]] <- CalculateCentroidDistance(PCs[[i]], withSD = TRUE, PC_SD[[i]])
}

# summary
mean <- c()
sd <- c()

for (i in 1:length(centroid_distances)) {
  mean[i] <- mean(centroid_distances[[i]])
  sd[i] <- sd(centroid_distances[[i]])
}
#
#cell_count <- as.data.frame(table(seu_reed_normal_LP@meta.data$donor_id))
centroid_sum_LP <- data.frame(mean = mean, sd = sd, patient_id = normal_ID, group = c(rep("LP", times = length(centroid_distances))))


### Normal HR ------
# get IDs
normal_ID <- as.character(unique(seu_reed_normal_HR@meta.data$donor_id))
# Split so by patient
seu_reed_normal_HR_split <- SplitObject(seu_reed_normal_HR, split.by = "donor_id")

### Distance analysis
## get PCA coordinates
# initialize list to store df and SD for PCs
PCs <- vector("list", length = length(normal_ID)) # PCs
PC_SD <- vector("list", length = length(normal_ID)) # SD of PCs

# extract PCs and SDs per patient in for loop
for (i in 1:length(seu_reed_normal_HR_split)) {
  # split patients
  patient <- seu_reed_normal_HR_split[[i]]
    # seurat pipeline
    patient <- RunSeuratPipeline(patient)
    # get PCs and SDs
    PCs[[i]] <- GetPCs(patient)
    PC_SD[[i]] <- GetSDs(patient, length(PCs))
}
## calculate distance to centroid with SD correction
# calculate centroid
# initiate list
centroid_distances <- vector("list", length = length(PCs))
#
for (i in 1:length(PCs)) {
  centroid_distances[[i]] <- CalculateCentroidDistance(PCs[[i]], withSD = TRUE, PC_SD[[i]])
}

# summary
mean <- c()
sd <- c()

for (i in 1:length(centroid_distances)) {
  mean[i] <- mean(centroid_distances[[i]])
  sd[i] <- sd(centroid_distances[[i]])
}
#
#cell_count <- as.data.frame(table(seu_reed_normal_HR@meta.data$donor_id))
centroid_sum_HR <- data.frame(mean = mean, sd = sd, patient_id = normal_ID, group = c(rep("HR", times = length(centroid_distances))))



#----------------------------
# do mean of subtypes:
centroid_sum_N_mean <- rbind(centroid_sum_B, centroid_sum_LP, centroid_sum_HR)

#### Normal vs Normal subtypes
centroid_sum <- rbind(centroid_sum_N, centroid_sum_B, centroid_sum_LP, centroid_sum_HR)

## plot

p <- ggbarplot(centroid_sum, x = "group", y = "mean", 
               add = c("mean_sd", "jitter"),
               fill = "group", 
               palette = c("#5c8d92", "#b8d7ac", "#a3cdc7", "#97b5c3"),
               xlab = "Cell type",
               ylab = "Weighted Mean CD",
               position = position_dodge(0.8)) +
  theme(legend.position = "none")

p

#setwd("D:/Dropbox/Master Thesis/Methods_transcript/Centroid_distance/Reed")
#save(centroid_sum, file = "centroid_sum.RData")

#setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Real/Reed")
#ggsave(filename = "Reed_wCD_NvsN.tiff", plot = p, width = 4, height = 2.5, dpi = 1200)


### One-way Anova with Dunnett's test for multiple comparisons
centroid_sum$group <- factor(centroid_sum$group)
centroid_sum$group <- relevel(centroid_sum$group, ref = "All Epi") # set All Epi as reference group

anova_result <- aov(mean ~ group, data = centroid_sum)
summary(anova_result)
dunnett_test <- glht(anova_result, linfct = mcp(group = "Dunnett"))
summary(dunnett_test)
pvalues <- as.vector(summary(dunnett_test)$test$pvalues)



### Plots with significance labels 
sig_df <- data.frame(
  group1 = c("All Epi", "All Epi", "All Epi"),
  group2 = c("Basal", "LP", "HR"),
  y.position = c(50, 55, 60),  # change these values as needed
  p.adj = pvalues
)

# convert p-values to star labels
sig_df$label <- ifelse(sig_df$p.adj < 0.001, "***", 
                  ifelse(sig_df$p.adj < 0.01, "**",
                  ifelse(sig_df$p.adj < 0.05, "*", "ns")))

centroid_sum <- centroid_sum %>% mutate(group = factor(group, levels = c("All Epi", "Basal", "LP", "HR")))
p <- ggbarplot(centroid_sum, x = "group", y = "mean", 
          add = c("mean_sd", "jitter"),
          fill = "group", 
          palette = c("#5c8d92", "#b8d7ac", "#a3cdc7", "#97b5c3"),
          xlab = "Group",
          ylab = "Weighted Mean CD",
          ylim = c(0,70),
          position = position_dodge(0.8)) +
  stat_pvalue_manual(sig_df, label = "label", tip.length = 0.01) +
  theme(legend.position = "none")
p

setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Real/Reed")
ggsave(filename = "Reed_wCD_NvsN.tiff", plot = p, width = 4, height = 2.5, dpi = 1200)

```
