### Figure 12C

---
title: "BubbleTree_Shannon_Moorman"
output: html_document
date: "2025-02-26"
---

```{r setup, include=FALSE}
knitr::knit_global()
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r load_libraries, include=FALSE}
# Load required package
#BiocManager::install("scBubbletree")
library(scBubbletree)
library(ggplot2)
library(ggtree)
library(patchwork)
#BiocManager::install("glmGamPoi")
# install sctransform from Github
#install.packages("sctransform")
library(Seurat)
library(patchwork)
library(dplyr)
library(ggplot2)
library(sctransform)
library(ggpubr)

# load data
# set working directory
setwd("D:/Dropbox/Master Thesis/Datasets/Moorman")

# load data
Seu_Moorman_Tumor <- readRDS("D:/Dropbox/Master Thesis/Datasets/Moorman/Seu_Moorman_Tumor.rds")
Seu_Moorman_Epi <- readRDS("D:/Dropbox/Master Thesis/Datasets/Moorman/Seu_Moorman_Epi.rds")
```


```{r QC}
# QC
#### Tumors
Seu_Moorman_Tumor <- subset(Seu_Moorman_Tumor, subset = Low.Quality == "False")
Seu_Moorman_Tumor <- subset(Seu_Moorman_Tumor, subset = nFeature_RNA > 250)

# keep only patients with > 50 cells in PT/Met
patient_counts <- table(Seu_Moorman_Tumor@meta.data[["Tumor.Status"]], Seu_Moorman_Tumor@meta.data[["Patient"]])
patients_to_keep <- names(which(patient_counts["Primary Tumor", ] > 50 & patient_counts["Metastasis", ] > 50))

# Filter the Seurat object
Seu_Moorman_Tumor <- subset(Seu_Moorman_Tumor, subset = Patient %in% patients_to_keep)


# QC
### Epi
Seu_Moorman_Epi <- subset(Seu_Moorman_Epi, subset = nFeature_RNA > 250)

# keep only patients with > 50 cells
patient_counts <- table(Seu_Moorman_Epi@meta.data[["Patient"]])
patients_to_keep <- names(which(patient_counts > 50))

# Filter the Seurat object
Seu_Moorman_Epi <- subset(Seu_Moorman_Epi, subset = Patient %in% patients_to_keep)

```


```{r functions}
select_dims <- function(object) {
  pct <- object[["pca"]]@stdev / sum(object[["pca"]]@stdev) * 100
  PCopt <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1
  return(1:PCopt)
}

scBubblePlotPipeline <- function(d){
  # Select the 5,000 most variable genes
  d <- FindVariableFeatures(object = d, selection.method = "vst", nfeatures = 5000)
  # Normalize the data using SCTransform
  d <- SCTransform(d, variable.features.n = 5000)
  # Run PCA
  d <- RunPCA(object = d, npcs = 50, features = VariableFeatures(object = d))
  # select optimal dims
  selected_dims <- select_dims(d)
  
  ### scBubbleTree
    # Extract the PCA embeddings
    A <- d@reductions$pca@cell.embeddings[, 1:length(selected_dims)]
    m <- d@meta.data
    d_ccl <- list(A = A, m = m)
    
    #k-means
    b_k <- get_k(B_gap = 10,
             ks = 1:30, # no. of ks
             x = A, # input matrix
             n_start = 50, 
             iter_max = 100,
             kmeans_algorithm = "MacQueen", 
             cores = 2)
    
    ## find optimal k
    gap_stats <- b_k$gap_stats_summary
    gap_diff <- diff(gap_stats$gap_mean) / gap_stats$gap_mean[-length(gap_stats$gap_mean)]
    optimal_k <- which(gap_diff < 0.01)[1] # First k where % change < 1%
    
    k <- get_bubbletree_kmeans(x = A,
                           k = optimal_k,
                           cores = 1,
                           B = 300,
                           N_eff = 200,
                           round_digits = 1,
                           show_simple_count = FALSE,
                           kmeans_algorithm = "MacQueen")
    return(k)
}


```

```{r run SE}
### PT ---------------
Seu_Moorman_Tumor_PT <- subset(Seu_Moorman_Tumor, subset = Tumor.Status == "Primary Tumor")

# get IDs
patient_id <- as.character(unique(Seu_Moorman_Tumor_PT@meta.data$Patient))
# Split by patient_id
Seu_Moorman_Tumor_PT_split <- SplitObject(Seu_Moorman_Tumor_PT, split.by = "Patient")

### Biodiversity - Shannon Entropy
# 1. Run scBubbleTree pipeline (k-means, with threshold of 1%)
  # create list to store trees after scBubbleTree pipeline
  trees_list <- vector("list", length = length(patient_id))
  
  # Run scBubbleTree for each tumor
  for (i in 1:length(Seu_Moorman_Tumor_PT_split)) {
    # split patients
    tumor <- Seu_Moorman_Tumor_PT_split[[i]]
    # run scBubbleTree pipeline
    trees_list[[i]] <- tryCatch(
    scBubblePlotPipeline(tumor),
    error = function(e) if (grepl("k must be a positive integer", e$message)) 0 else stop(e)
  )
}
  # save
  Moorman_PT_Trees_List <- trees_list
  names(Moorman_PT_Trees_List) <- patient_id
  #save(Moorman_PT_Trees_List, file = "Moorman_PT_Trees_List.RData")



### Met ---------------
Seu_Moorman_Tumor_M <- subset(Seu_Moorman_Tumor, subset = Tumor.Status == "Metastasis")

# get IDs
patient_id <- as.character(unique(Seu_Moorman_Tumor_M@meta.data$Patient))
# Split by patient_id
Seu_Moorman_Tumor_M_split <- SplitObject(Seu_Moorman_Tumor_M, split.by = "Patient")

### Biodiversity - Shannon Entropy
# 1. Run scBubbleTree pipeline (k-means, with threshold of 1%)
  # create list to store trees after scBubbleTree pipeline
  trees_list <- vector("list", length = length(patient_id))
  
  # Run scBubbleTree for each tumor
  for (i in 1:length(Seu_Moorman_Tumor_M_split)) {
    # split patients
    tumor <- Seu_Moorman_Tumor_M_split[[i]]
    # run scBubbleTree pipeline
    trees_list[[i]] <- tryCatch(
    scBubblePlotPipeline(tumor),
    error = function(e) if (grepl("k must be a positive integer", e$message)) 0 else stop(e) # there was an error with kG188 -> manually reran this line
  )
}
  # save
  Moorman_Met_Trees_List <- trees_list
  names(Moorman_Met_Trees_List) <- patient_id
  #save(Moorman_Met_Trees_List, file = "Moorman_Met_Trees_List.RData")
  

### Epi ---------------
### N ---------------
# get IDs
patient_id <- as.character(unique(Seu_Moorman_Epi@meta.data$Patient))
# Split by patient_id
Seu_Moorman_Epi_split <- SplitObject(Seu_Moorman_Epi, split.by = "Patient")

### Biodiversity - Shannon Entropy
# 1. Run scBubbleTree pipeline (k-means, with threshold of 1%)
  # create list to store trees after scBubbleTree pipeline
  trees_list <- vector("list", length = length(patient_id))
  
  # Run scBubbleTree for each tumor
  for (i in 1:length(Seu_Moorman_Epi_split)) {
    # split patients
    tumor <- Seu_Moorman_Epi_split[[i]]
    # run scBubbleTree pipeline
    trees_list[[i]] <- tryCatch(
    scBubblePlotPipeline(tumor),
    error = function(e) if (grepl("k must be a positive integer", e$message)) 0 else stop(e)
  )
}
  # save
  #Moorman_N_Trees_List <- trees_list
  #names(Moorman_N_Trees_List) <- patient_id
  #save(Moorman_N_Trees_List, file = "Moorman_N_Trees_List.RData")
  
 

```


```{r Vizualitation}

### PT ----
  trees_list <-   Moorman_PT_Trees_List
  patient_id <- names(Moorman_PT_Trees_List)
  
# 2. Calculate Shannon-Entropy from proportions
  # create vector to store Shannon Entropy
  Shannon_list <- c()
    
  # Calc. SE
  for (i in 1:length(trees_list)) {
    # split trees
    tree <- trees_list[[i]]
    
    # Check if "tree_meta" exists in the tree
    if ("tree_meta" %in% names(tree)) {
      results_df <- tree[["tree_meta"]]
      
      # Calculate Shannon entropy
      probs <- results_df$p
      Shannon_list[i] <- -sum(probs * log2(probs))
    } else {
      # Assign 0 if "tree_meta" is not present
      Shannon_list[i] <- 0
    }
  }
  Moorman_PT_Shannon_list <- Shannon_list
  names(Moorman_PT_Shannon_list) <- patient_id
  
# Visualization
Moorman_PTSE_results <- data.frame(SE = Moorman_PT_Shannon_list, 
                                       patient = patient_id,
                                     Tissue = c(rep("PT", times = length(Moorman_PT_Shannon_list))))



### Met ---
  trees_list <-   Moorman_Met_Trees_List
  patient_id <- names(Moorman_Met_Trees_List)
  
# 2. Calculate Shannon-Entropy from proportions
  # create vector to store Shannon Entropy
  Shannon_list <- c()
    
  # Calc. SE
  for (i in 1:length(trees_list)) {
    # split trees
    tree <- trees_list[[i]]
    
    # Check if "tree_meta" exists in the tree
    if ("tree_meta" %in% names(tree)) {
      results_df <- tree[["tree_meta"]]
      
      # Calculate Shannon entropy
      probs <- results_df$p
      Shannon_list[i] <- -sum(probs * log2(probs))
    } else {
      # Assign 0 if "tree_meta" is not present
      Shannon_list[i] <- 0
    }
  }
  Moorman_Met_Shannon_list <- Shannon_list
  names(Moorman_Met_Shannon_list) <- patient_id
  
# Visualization
Moorman_MetSE_results <- data.frame(SE = Moorman_Met_Shannon_list, 
                                       patient = patient_id,
                                     Tissue = c(rep("Met", times = length(Moorman_Met_Shannon_list))))


### combine
Moorman_AllSE_results <- rbind(Moorman_PTSE_results, Moorman_MetSE_results)
Moorman_AllSE_results <- Moorman_AllSE_results[!is.na(Moorman_AllSE_results$patient), ]
Moorman_AllSE_results <- Moorman_AllSE_results %>% mutate(Tissue = factor(Tissue, levels = c("PT", "Met")))
Moorman_AllSE_results$patient <- as.factor(Moorman_AllSE_results$patient)



### Statistical test
# check normality
shapiro.test(Moorman_AllSE_results$SE[Moorman_AllSE_results$Tissue == "PT"]) #-> not normal
shapiro.test(Moorman_AllSE_results$SE[Moorman_AllSE_results$Tissue == "Met"]) #-> not normal

# Paired MWU-test
paired_data <- SE_Winkler_SS2_PTvsMet[SE_Winkler_SS2_PTvsMet$tumor_id %in% 
                                      SE_Winkler_SS2_PTvsMet$tumor_id[duplicated(SE_Winkler_SS2_PTvsMet$tumor_id)], ]

pt_values <- paired_data$SE[paired_data$Tissue == "PT"]
met_values <- paired_data$SE[paired_data$Tissue == "Met"]

# Perform paired MWU
wilcox_test <- wilcox.test(pt_values, met_values, paired = TRUE)
pvalues <- wilcox_test$p.value


### Plots with significance labels 
sig_df <- data.frame(
      group1 = "PT",
      group2 = "Met",
      y.position = 5,  # change these values as needed
      p.adj = pvalues
)
    
    # convert p-values to star labels
    sig_df$label <- ifelse(sig_df$p.adj < 0.001, "***", 
                      ifelse(sig_df$p.adj < 0.01, "**",
                      ifelse(sig_df$p.adj < 0.05, "*", "ns")))
    
    
p <- ggplot(Moorman_AllSE_results, aes(x = Tissue, y = SE)) + 
  geom_boxplot(aes(fill = Tissue), width = 0.5, color = "black", outlier.shape = NA) +  
  geom_jitter(aes(group = patient), width = 0.01, size = 1, alpha = 1) +  
   geom_line(aes(group = patient), color = "#2b2d42", linetype = "dashed", size = 0.5, alpha = 0.8) +
  scale_fill_manual(values = c("PT" = "goldenrod2", "Met" = "indianred2")) +  
  theme_classic() +
  ylim(0,5.2) +
  stat_pvalue_manual(sig_df, label = "label", tip.length = 0.01) +
  theme(axis.text.x = element_text(size = 12, colour = "black"),
        axis.text.y = element_text(size = 12, colour = "black"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.position = "right") +
  labs(x = "Tissue", y = "Shannon Entropy")
p


setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Real/Moorman")
ggsave(filename = "Moorman_SE_PTvsMet_sig.tiff", plot = p,width = 3.5, height = 2.5, dpi = 1200)    
      
```


```{r >100cells}

patients_to_keep <- names(which(patient_counts["Primary Tumor", ] > 100 & patient_counts["Metastasis", ] > 100))

### PT ----
  trees_list <-   Moorman_PT_Trees_List
  patient_id <- names(Moorman_PT_Trees_List)
  
# 2. Calculate Shannon-Entropy from proportions
  # create vector to store Shannon Entropy
  Shannon_list <- c()
    
  # Calc. SE
  for (i in 1:length(trees_list)) {
    # split trees
    tree <- trees_list[[i]]
    
    # Check if "tree_meta" exists in the tree
    if ("tree_meta" %in% names(tree)) {
      results_df <- tree[["tree_meta"]]
      
      # Calculate Shannon entropy
      probs <- results_df$p
      Shannon_list[i] <- -sum(probs * log2(probs))
    } else {
      # Assign 0 if "tree_meta" is not present
      Shannon_list[i] <- 0
    }
  }
  Moorman_PT_Shannon_list <- Shannon_list
  names(Moorman_PT_Shannon_list) <- patient_id
  
# Visualization
Moorman_PTSE_results <- data.frame(SE = Moorman_PT_Shannon_list, 
                                       patient = patient_id,
                                     Tissue = c(rep("PT", times = length(Moorman_PT_Shannon_list))))



### Met ---
  trees_list <-   Moorman_Met_Trees_List
  patient_id <- names(Moorman_Met_Trees_List)
  
# 2. Calculate Shannon-Entropy from proportions
  # create vector to store Shannon Entropy
  Shannon_list <- c()
    
  # Calc. SE
  for (i in 1:length(trees_list)) {
    # split trees
    tree <- trees_list[[i]]
    
    # Check if "tree_meta" exists in the tree
    if ("tree_meta" %in% names(tree)) {
      results_df <- tree[["tree_meta"]]
      
      # Calculate Shannon entropy
      probs <- results_df$p
      Shannon_list[i] <- -sum(probs * log2(probs))
    } else {
      # Assign 0 if "tree_meta" is not present
      Shannon_list[i] <- 0
    }
  }
  Moorman_Met_Shannon_list <- Shannon_list
  names(Moorman_Met_Shannon_list) <- patient_id
  
# Visualization
Moorman_MetSE_results <- data.frame(SE = Moorman_Met_Shannon_list, 
                                       patient = patient_id,
                                     Tissue = c(rep("Met", times = length(Moorman_Met_Shannon_list))))



### combine
Moorman_AllSE_results <- rbind(Moorman_PTSE_results, Moorman_MetSE_results)
Moorman_AllSE_results <- Moorman_AllSE_results[!is.na(Moorman_AllSE_results$patient), ]
Moorman_AllSE_results <- Moorman_AllSE_results %>% mutate(Tissue = factor(Tissue, levels = c("PT", "Met")))
# subset patients with > cells
Moorman_AllSE_results <- Moorman_AllSE_results[Moorman_AllSE_results$patient %in% patients_to_keep,]
Moorman_AllSE_results$patient <- as.factor(Moorman_AllSE_results$patient)



### Statistical test
# check normality
shapiro.test(Moorman_AllSE_results$SE[Moorman_AllSE_results$Tissue == "PT"]) #-> not normal
shapiro.test(Moorman_AllSE_results$SE[Moorman_AllSE_results$Tissue == "Met"]) #-> not normal

# Paired MWU-test
paired_data <- SE_Winkler_SS2_PTvsMet[SE_Winkler_SS2_PTvsMet$tumor_id %in% 
                                      SE_Winkler_SS2_PTvsMet$tumor_id[duplicated(SE_Winkler_SS2_PTvsMet$tumor_id)], ]

pt_values <- paired_data$SE[paired_data$Tissue == "PT"]
met_values <- paired_data$SE[paired_data$Tissue == "Met"]

# Perform paired MWU
wilcox_test <- wilcox.test(pt_values, met_values, paired = TRUE)
pvalues <- wilcox_test$p.value


### Plots with significance labels 
sig_df <- data.frame(
      group1 = "PT",
      group2 = "Met",
      y.position = 5,  # change these values as needed
      p.adj = pvalues
)
    
    # convert p-values to star labels
    sig_df$label <- ifelse(sig_df$p.adj < 0.001, "***", 
                      ifelse(sig_df$p.adj < 0.01, "**",
                      ifelse(sig_df$p.adj < 0.05, "*", "ns")))
    
    
p <- ggplot(Moorman_AllSE_results, aes(x = Tissue, y = SE)) + 
  geom_boxplot(aes(fill = Tissue), width = 0.5, color = "black", outlier.shape = NA) +  
  geom_jitter(aes(group = patient), width = 0.01, size = 1, alpha = 1) +  
   geom_line(aes(group = patient), color = "#2b2d42", linetype = "dashed", size = 0.5, alpha = 0.8) +
  scale_fill_manual(values = c("PT" = "goldenrod2", "Met" = "indianred2")) +  
  theme_classic() +
  ylim(0,5.2) +
  stat_pvalue_manual(sig_df, label = "label", tip.length = 0.01) +
  theme(axis.text.x = element_text(size = 12, colour = "black"),
        axis.text.y = element_text(size = 12, colour = "black"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.position = "right") +
  labs(x = "Tissue", y = "Shannon Entropy")
p


setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Real/Moorman")
ggsave(filename = "Moorman_SE_PTvsMet_sig_100cells.tiff", plot = p ,width = 3.5, height = 2.5, dpi = 1200)  

```

