### Figure 11E + 12C

---
title: "BubbleTreeShannon_Winkler"
output: html_document
date: "2025-01-10"
---

```{r setup, include=FALSE}
knitr::knit_global()
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r load_libraries, include=FALSE}
# Load required package
#BiocManager::install("scBubbletree")
library(scBubbletree)
library(ggplot2)
library(ggtree)
library(patchwork)
#BiocManager::install("glmGamPoi")
# install sctransform from Github
#install.packages("sctransform")
library(Seurat)
library(patchwork)
library(dplyr)
library(ggplot2)
library(sctransform)
library(ggpubr)

# load data
load("D:/Dropbox/Master Thesis/PDX_data/seu_ss2.RData")

setwd("D:/Dropbox/Master Thesis/Methods_transcript/Biodiversity/BubbleTree/Winkler")
```


```{r QC}
# ss2
seu_ss2 <- subset(seu_ss2, subset = n_genes > 250)

```


```{r functions}
select_dims <- function(object) {
  pct <- object[["pca"]]@stdev / sum(object[["pca"]]@stdev) * 100
  PCopt <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1
  return(1:PCopt)
}

scBubblePlotPipeline <- function(d){
  # Select the 5,000 most variable genes
  d <- FindVariableFeatures(object = d, selection.method = "vst", nfeatures = 5000)
  # Normalize the data using SCTransform
  d <- SCTransform(d, variable.features.n = 5000)
  # Run PCA
  d <- RunPCA(object = d, npcs = 50, features = VariableFeatures(object = d))
  # select optimal dims
  selected_dims <- select_dims(d)
  
  ### scBubbleTree
    # Extract the PCA embeddings
    A <- d@reductions$pca@cell.embeddings[, 1:length(selected_dims)]
    m <- d@meta.data
    d_ccl <- list(A = A, m = m)
    
    #k-means
    b_k <- get_k(B_gap = 10,
             ks = 1:30, # no. of ks
             x = A, # input matrix
             n_start = 50, 
             iter_max = 100,
             kmeans_algorithm = "MacQueen", 
             cores = 2)
    
    ## find optimal k
    gap_stats <- b_k$gap_stats_summary
    gap_diff <- diff(gap_stats$gap_mean) / gap_stats$gap_mean[-length(gap_stats$gap_mean)]
    optimal_k <- which(gap_diff < 0.01)[1] # First k where % change < 1%
    
    k <- get_bubbletree_kmeans(x = A,
                           k = optimal_k,
                           cores = 1,
                           B = 300,
                           N_eff = 200,
                           round_digits = 1,
                           show_simple_count = FALSE,
                           kmeans_algorithm = "MacQueen")
    return(k)
}


```


```{r run ss2}

### Tumor ---------------
seu_ss2_tumor <- subset(seu_ss2, subset = sort == "Tumor")

# get IDs
tumor_ID <- as.character(unique(seu_ss2_tumor@meta.data$Tumor_ID))
# Split by tumor_id
seu_ss2_tumor_split <- SplitObject(seu_ss2_tumor, split.by = "Tumor_ID")
# Filter the list, keeping only elements with 50 or more cells
seu_ss2_tumor_split <- seu_ss2_tumor_split[sapply(seu_ss2_tumor_split, function(x) ncol(x) >= 50)]
# update tumor_id
tumor_ID <- names(seu_ss2_tumor_split)



### Biodiversity - Shannon Entropy
# 1. Run scBubbleTree pipeline (k-means, with threshold of 1%)
  # create list to store trees after scBubbleTree pipeline
  trees_list <- vector("list", length = length(tumor_ID))
  
  # Run scBubbleTree for each tumor
  for (i in 1:length(seu_ss2_tumor_split)) {
    # split patients
    tumor <- seu_ss2_tumor_split[[i]]
    # run scBubbleTree pipeline
    trees_list[[i]] <- tryCatch(
    scBubblePlotPipeline(tumor),
    error = function(e) if (grepl("k must be a positive integer", e$message)) 0 else stop(e)
  )
}
  # save
  #WinklerSS2_Trees_List <- trees_list
  #names(WinklerSS2_Trees_List) <- tumor_ID
  #save(WinklerSS2_Trees_List, file = "WinklerSS2_Trees_List.RData")
  
  trees_list <- WinklerSS2_Trees_List
  tumor_ID <- names(WinklerSS2_Trees_List)
  
# 2. Calculate Shannon-Entropy from proportions
  # create vector to store Shannon Entropy
  Shannon_list <- c()
    
  # Calc. SE
  for (i in 1:length(trees_list)) {
    # split trees
    tree <- trees_list[[i]]
    
    # Check if "tree_meta" exists in the tree
    if ("tree_meta" %in% names(tree)) {
      results_df <- tree[["tree_meta"]]
      
      # Calculate Shannon entropy
      probs <- results_df$p
      Shannon_list[i] <- -sum(probs * log2(probs))
    } else {
      # Assign 0 if "tree_meta" is not present
      Shannon_list[i] <- 0
    }
  }
  WinklerSS2_Shannon_list <- Shannon_list
  names(WinklerSS2_Shannon_list) <- tumor_ID
  
  
# Visualization
Winkler_SS2_SE_results <- data.frame(SE = WinklerSS2_Shannon_list, 
                                      tumor_id = tumor_ID,
                                      group = c(rep("10x", times = length(WinklerSS2_Shannon_list))),
                                     Tissue = c(rep("PT", times = length(WinklerSS2_Shannon_list))))

meta_data_table <- as.data.frame(table(seu_ss2_tumor@meta.data$metastatic_potential_group, seu_ss2_tumor@meta.data$Tumor_ID))
colnames(meta_data_table) <- c("met_pot", "tumor_id", "count")
meta_data_table <- meta_data_table[meta_data_table$count > 0, ]
Winkler_SS2_SE_results <- merge(Winkler_SS2_SE_results, meta_data_table[, c("met_pot", "tumor_id")], by = "tumor_id", all.x = TRUE)

# change anno
    Winkler_SS2_SE_results$met_pot <- gsub("low", "Low", Winkler_SS2_SE_results$met_pot)
    Winkler_SS2_SE_results$met_pot <- gsub("intermediate", "Moderate", Winkler_SS2_SE_results$met_pot)
    Winkler_SS2_SE_results$met_pot <- gsub("high", "High", Winkler_SS2_SE_results$met_pot)
Winkler_SS2_SE_results <- Winkler_SS2_SE_results %>% mutate(met_pot = factor(met_pot, levels = c("Low", "Moderate", "High")))

ggplot(Winkler_SS2_SE_results, aes(x = met_pot, y = SE, fill = met_pot)) +
  geom_boxplot(outlier.shape = NA) +  # Boxplot without outliers
  geom_jitter(width = 0.2, size = 2, color = "black") +  # Jittered points with black color
  scale_fill_manual(values = c("#bfc4c6", "#6d7486", "#2b2d42")) +  # Custom palette
  labs(
    x = "Metastatic Potential",
    y = "Shannon Entropy",
    fill = "Metastatic Potential"
  ) +
  theme_minimal() +
  theme(
    legend.position = "right",
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

p <- ggboxplot(Winkler_SS2_SE_results, x = "met_pot", y = "SE",
          fill = "met_pot", 
          palette = c("#bfc4c6", "#6d7486", "#2b2d42"),
          xlab = "Metastatic Potential",
          ylab = "Shannon Entropy",
          add = "jitter") +
  theme(legend.position = "none") +
  coord_cartesian(ylim = c(0, 4.5))

p

setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Winkler/SmartSeq2")
ggsave(filename = "Winkler_SE_ss2.tiff", plot = p, width = 3, height = 2.5, dpi = 1200)

      
#setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Winkler")
#ggsave(filename = "Winkler_SE_ss2.tiff", plot = p, width = 3, height = 2.5, dpi = 1200)

```


      ```{r run ss2 mets}

### Met ---------------
seu_ss2_met <- subset(seu_ss2, subset = sort == "Metastatic")

# get IDs
tumor_ID <- as.character(unique(seu_ss2_met@meta.data$Tumor_ID))
# Split by tumor_id
seu_ss2_met_split <- SplitObject(seu_ss2_met, split.by = "Tumor_ID")
# Filter the list, keeping only elements with 50 or more cells
seu_ss2_met_split <- seu_ss2_met_split[sapply(seu_ss2_met_split, function(x) ncol(x) >= 50)]
# update tumor_id
tumor_ID <- names(seu_ss2_met_split)



### Biodiversity - Shannon Entropy
# 1. Run scBubbleTree pipeline (k-means, with threshold of 1%)
  # create list to store trees after scBubbleTree pipeline
  trees_list <- vector("list", length = length(tumor_ID))
  
  # Run scBubbleTree for each tumor
  for (i in 1:length(seu_ss2_met_split)) {
    # split patients
    tumor <- seu_ss2_met_split[[i]]
    # run scBubbleTree pipeline
    trees_list[[i]] <- tryCatch(
    scBubblePlotPipeline(tumor),
    error = function(e) if (grepl("k must be a positive integer", e$message)) 0 else stop(e)
  )
}
  # save
  WinklerSS2mets_Trees_List <- trees_list
  names(WinklerSS2mets_Trees_List) <- tumor_ID
  save(WinklerSS2mets_Trees_List, file = "WinklerSS2mets_Trees_List.RData")
  
  trees_list <- WinklerSS2mets_Trees_List
  tumor_ID <- names(WinklerSS2mets_Trees_List)
  
# 2. Calculate Shannon-Entropy from proportions
  # create vector to store Shannon Entropy
  Shannon_list <- c()
    
  # Calc. SE
  for (i in 1:length(trees_list)) {
    # split trees
    tree <- trees_list[[i]]
    
    # Check if "tree_meta" exists in the tree
    if ("tree_meta" %in% names(tree)) {
      results_df <- tree[["tree_meta"]]
      
      # Calculate Shannon entropy
      probs <- results_df$p
      Shannon_list[i] <- -sum(probs * log2(probs))
    } else {
      # Assign 0 if "tree_meta" is not present
      Shannon_list[i] <- 0
    }
  }
  WinklerSS2met_Shannon_list <- Shannon_list
  names(WinklerSS2met_Shannon_list) <- tumor_ID
  

# Visualization
Winkler_SS2_met_SE_results <- data.frame(SE = WinklerSS2met_Shannon_list, 
                                       tumor_id = tumor_ID,
                                       group = c(rep("10x", times = length(WinklerSS2met_Shannon_list))),
                                       Tissue = c(rep("Met", times = length(WinklerSS2met_Shannon_list))))

meta_data_table <- as.data.frame(table(seu_ss2_tumor@meta.data$metastatic_potential_group, seu_ss2_tumor@meta.data$Tumor_ID))
colnames(meta_data_table) <- c("met_pot", "tumor_id", "count")
meta_data_table <- meta_data_table[meta_data_table$count > 0, ]
Winkler_SS2_met_SE_results <- merge(Winkler_SS2_met_SE_results, meta_data_table[, c("met_pot", "tumor_id")], by = "tumor_id", all.x = TRUE)

# change anno
    Winkler_SS2_met_SE_results$met_pot <- gsub("low", "Low", Winkler_SS2_met_SE_results$met_pot)
    Winkler_SS2_met_SE_results$met_pot <- gsub("intermediate", "Moderate", Winkler_SS2_met_SE_results$met_pot)
    Winkler_SS2_met_SE_results$met_pot <- gsub("high", "High", Winkler_SS2_met_SE_results$met_pot)
Winkler_SS2_met_SE_results <- Winkler_SS2_met_SE_results %>% mutate(met_pot = factor(met_pot, levels = c("Low", "Moderate", "High")))

# combine with PT
SE_Winkler_SS2_filtered <- Winkler_SS2_SE_results[Winkler_SS2_SE_results$tumor_id %in% Winkler_SS2_met_SE_results$tumor_id, ]
SE_Winkler_SS2_filtered <- SE_Winkler_SS2_filtered[, colnames(Winkler_SS2_met_SE_results)]
SE_Winkler_SS2_PTvsMet <- rbind(SE_Winkler_SS2_filtered, Winkler_SS2_met_SE_results)

SE_Winkler_SS2_PTvsMet$Tissue <- factor(SE_Winkler_SS2_PTvsMet$Tissue, levels = c("PT", "Met"))
SE_Winkler_SS2_PTvsMet$met_pot <- factor(SE_Winkler_SS2_PTvsMet$met_pot, levels = c("Low", "Moderate", "High"))
SE_Winkler_SS2_PTvsMet$tumor_id <- as.factor(SE_Winkler_SS2_PTvsMet$tumor_id)
  

# plot
p <- ggplot(SE_Winkler_SS2_PTvsMet, aes(x = Tissue, y = SE)) + 
  geom_boxplot(aes(fill = Tissue), width = 0.5, color = "black", outlier.shape = NA) +  
  geom_jitter(aes(group = tumor_id), width = 0.01, size = 1, alpha = 1) +  
  geom_line(aes(group = tumor_id, color = met_pot, linetype = met_pot), size = 0.5, alpha = 0.8) + 
  scale_fill_manual(values = c("PT" = "goldenrod2", "Met" = "indianred2")) +  
  scale_color_manual(values = c("Low" = "#2b2d42", "Moderate" = "#2b2d42", "High" = "#2b2d42")) +  
  scale_linetype_manual(values = c("Low" = "dotted", "Moderate" = "dashed", "High" = "solid")) + 
  theme_classic() +
  theme(axis.text.x = element_text(size = 12, colour = "black"),
        axis.text.y = element_text(size = 12, colour = "black"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.position = "right") +
  labs(x = "Tissue", y = "Shannon Entropy", color = "Metastatic\nPotential", linetype = "Metastatic\nPotential")
p

setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Winkler")
ggsave(filename = "Winkler_SE_ss2_PTvsMet.tiff", plot = p,width = 3.5, height = 2.5, dpi = 1200)



### Statistical test
# check normality
shapiro.test(SE_Winkler_SS2_PTvsMet$SE[SE_Winkler_SS2_PTvsMet$Tissue == "PT"])
shapiro.test(SE_Winkler_SS2_PTvsMet$SE[SE_Winkler_SS2_PTvsMet$Tissue == "Met"])

# Paired t-test
paired_data <- SE_Winkler_SS2_PTvsMet[SE_Winkler_SS2_PTvsMet$tumor_id %in% 
                                      SE_Winkler_SS2_PTvsMet$tumor_id[duplicated(SE_Winkler_SS2_PTvsMet$tumor_id)], ]

pt_values <- paired_data$SE[paired_data$Tissue == "PT"]
met_values <- paired_data$SE[paired_data$Tissue == "Met"]

# Perform paired t-test
ttest <- t.test(pt_values, met_values, paired = TRUE)
pvalues <- ttest$p.value

### Plots with significance labels 
sig_df <- data.frame(
      group1 = "PT",
      group2 = "Met",
      y.position = 3.5,  # change these values as needed
      p.adj = pvalues
)
    
    # convert p-values to star labels
    sig_df$label <- ifelse(sig_df$p.adj < 0.001, "***", 
                      ifelse(sig_df$p.adj < 0.01, "**",
                      ifelse(sig_df$p.adj < 0.05, "*", "ns")))

p <- ggplot(SE_Winkler_SS2_PTvsMet, aes(x = Tissue, y = SE)) + 
  geom_boxplot(aes(fill = Tissue), width = 0.5, color = "black", outlier.shape = NA) +  
  geom_jitter(aes(group = tumor_id), width = 0.01, size = 1, alpha = 1) +  
  geom_line(aes(group = tumor_id, color = met_pot, linetype = met_pot), size = 0.5, alpha = 0.8) + 
  scale_fill_manual(values = c("PT" = "goldenrod2", "Met" = "indianred2")) +  
  scale_color_manual(values = c("Low" = "#2b2d42", "Moderate" = "#2b2d42", "High" = "#2b2d42")) +  
  scale_linetype_manual(values = c("Low" = "dotted", "Moderate" = "dashed", "High" = "solid")) + 
  theme_classic() +
  ylim(0,4) +
  stat_pvalue_manual(sig_df, label = "label", tip.length = 0.01) +
  theme(axis.text.x = element_text(size = 12, colour = "black"),
        axis.text.y = element_text(size = 12, colour = "black"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.position = "right") +
  labs(x = "Tissue", y = "Shannon Entropy", color = "Metastatic\nPotential", linetype = "Metastatic\nPotential")
p

setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Winkler")
ggsave(filename = "Winkler_SE_ss2_PTvsMet_sig.tiff", plot = p,width = 3.5, height = 2.5, dpi = 1200)
    
```

