### Figure 11C-D + 12B

---
title: "Centroid_dist_Winkler_optPCs"
output: html_document
date: "2024-10-21"
---

```{r setup, include=FALSE}
knitr::knit_global()
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r load_libraries, include=FALSE}
# Load required package
if (!requireNamespace("MASS", quietly = TRUE)) {
  install.packages("MASS")
}
library(Seurat)
library(ggplot2)
library(ggpmisc)
library(caret)
library(ggpubr)
library(dplyr)
library(RColorBrewer)
# set seed
set.seed(43)

# color palette

# load libraries
# set working directory
setwd("D:/Dropbox/Master Thesis/PDX_data")

load("D:/Dropbox/Master Thesis/PDX_data/seu_ss2.RData")
```

```{r QC}
### ss2
# filter
seu_ss2 <- subset(seu_ss2, subset = n_genes > 250)
table(seu_ss2@meta.data[["Tumor_ID"]], seu_ss2@meta.data[["sort"]])

```


```{r functions}
### Functions ###
## function: RunSeuratPipeline
RunSeuratPipeline <- function(seu_object){
  seu_object <- NormalizeData(seu_object, normalization.method = "LogNormalize", scale.factor = 10000)
  seu_object <- FindVariableFeatures(seu_object, selection.method = "vst", nfeatures = 2000)
  seu_object <- ScaleData(seu_object)
  seu_object <- RunPCA(seu_object, npcs = 30)
  return(seu_object)
}
## function: extract PCs and SDs
# extract PCs
GetPCs <- function(seu_object){
  # get optimal PC
  pct <- seu_object[["pca"]]@stdev / sum(seu_object[["pca"]]@stdev) * 100
  PCopt <- sort(which((pct[1:length(pct) - 1] - pct[2:length(pct)]) > 0.1), decreasing = T)[1] + 1
  pcs <- PCopt
  PCs <- as.data.frame(seu_object@reductions$pca@cell.embeddings[,c(1:pcs)])
  return(PCs)
}
# extract SDs
GetSDs <- function(seu_object, numPC){
  pca <- seu_object@reductions$pca
  total_variance <- seu_object@reductions$pca@misc$total.variance
  eigValues <- (pca@stdev)^2
  varExplained <- eigValues / total_variance
  SDs <- (varExplained * 100)[1:numPC]
  return(SDs)
}
## function: calculate centroid distance
CalculateCentroidDistance <- function(PCs, withSD = NULL, SDs = NULL){
  centroid_list <- as.vector(apply(PCs, 2, mean)) # calculate centroid for all PCs
  centroid_matrix <- sweep(PCs, 2, centroid_list) # create matrix with centroid in the center (by substraction of centroid list)
  # Calculate distance
  if (!is.null(withSD)) {
    distance <- sqrt(rowSums((sweep(centroid_matrix, 2, SDs, "*"))^2)) # with SD correction (if)
  } else {
    distance <- sqrt(rowSums(centroid_matrix^2)) # normal
  }
  distance <- as.matrix(distance)
  return(distance)
}
```

```{r SS2, fig.height=4, fig.width=8}
#### Cluster Analysis ####

### Tumor ---------------
seu_ss2_tumor <- subset(seu_ss2, subset = sort == "Tumor")

# get IDs
tumor_ID <- as.character(unique(seu_ss2_tumor@meta.data$Tumor_ID))
# Split by tumor_id
seu_ss2_tumor_split <- SplitObject(seu_ss2_tumor, split.by = "Tumor_ID")
# Filter the list, keeping only elements with 50 or more cells
seu_ss2_tumor_split <- seu_ss2_tumor_split[sapply(seu_ss2_tumor_split, function(x) ncol(x) >= 50)]
# update tumor_id
tumor_ID <- names(seu_ss2_tumor_split)

### Distance analysis
## get PCA coordinates
# initialize list to store df and SD for PCs
Winkler_PCs <- vector("list", length = length(tumor_ID)) # PCs
Winkler_PC_SD <- vector("list", length = length(tumor_ID)) # SD of PCs

# extract PCs and SDs per patient in for loop
for (i in 1:length(seu_ss2_tumor_split)) {
  # split patients
  tumor <- seu_ss2_tumor_split[[i]]
    # seurat pipeline
    tumor <- RunSeuratPipeline(tumor)
    # get PCs and SDs
    Winkler_PCs[[i]] <- GetPCs(tumor)
    Winkler_PC_SD[[i]] <- GetSDs(tumor, length(Winkler_PCs))
}
## calculate distance to centroid with SD correction
# calculate centroid
# initiate list
centroid_distances <- vector("list", length = length(Winkler_PCs))
#
for (i in 1:length(Winkler_PCs)) {
  centroid_distances[[i]] <- CalculateCentroidDistance(Winkler_PCs[[i]], withSD = TRUE, Winkler_PC_SD[[i]])
}

# save
#setwd("C:/Users/vali3/Dropbox/Master Thesis/Methods_transcript/Centroid_distance/Winkler")
#save(centroid_distances, file = "centroid_distances_ss2.RData")

# summary
mean <- c()
sd <- c()

for (i in 1:length(centroid_distances)) {
  mean[i] <- mean(centroid_distances[[i]])
  sd[i] <- sd(centroid_distances[[i]])
}
#
centroid_sum_Winkler_SS2 <- data.frame(mean = mean, 
                                       sd = sd, 
                                       tumor_id = tumor_ID,
                                       #PCs = sapply(Winkler_PCs, ncol),
                                       weighted = c(rep("yes", times = length(centroid_distances))),
                                       group = c(rep("SS2", times = length(centroid_distances))),
                                       Tissue = c(rep("PT", times = length(centroid_distances))))
# add metastatic potential
meta_data_table <- as.data.frame(table(seu_ss2@meta.data$metastatic_potential_group, seu_ss2@meta.data$Tumor_ID))
colnames(meta_data_table) <- c("met_pot", "tumor_id", "count")
meta_data_table <- meta_data_table[meta_data_table$count > 0, ]
meta_data_table <- meta_data_table[meta_data_table$tumor_id %in% tumor_ID,]
centroid_sum_Winkler_SS2 <- merge(centroid_sum_Winkler_SS2, meta_data_table[, c("met_pot", "tumor_id")], by = "tumor_id", all.x = TRUE)
    # change anno
    centroid_sum_Winkler_SS2$met_pot <- gsub("low", "Low", centroid_sum_Winkler_SS2$met_pot)
    centroid_sum_Winkler_SS2$met_pot <- gsub("intermediate", "Moderate", centroid_sum_Winkler_SS2$met_pot)
    centroid_sum_Winkler_SS2$met_pot <- gsub("high", "High", centroid_sum_Winkler_SS2$met_pot)

centroid_sum_Winkler_SS2 <- centroid_sum_Winkler_SS2 %>% mutate(met_pot = factor(met_pot, levels = c("Low", "Moderate", "High")))


## plot
p <- ggbarplot(centroid_sum_Winkler_SS2, x = "met_pot", y = "mean", 
          add = c("mean_sd", "jitter"),
          color = "black", fill = "met_pot", palette = c("#bfc4c6", "#6d7486", "#2b2d42"), 
          # old colors: c("#edf2f4", "#8d99ae", "#2b2d42")
          position = position_dodge(0.3),
          ylab = "Weighted Mean CD",
          xlab = "Metastatic Potential") +
          theme(legend.position = "none")
p


setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Winkler")
ggsave(filename = "WinklerSS2_CD_hist.tiff", plot = p, width = 3, height = 2.5, dpi = 1200)



### Anova
### One-way Anova with Tukey's test for multiple comparisons
centroid_sum_Winkler_SS2$met_pot <- factor(centroid_sum_Winkler_SS2$met_pot)
# Perform ANOVA
anova_result <- aov(mean ~ met_pot, data = centroid_sum_Winkler_SS2)
summary(anova_result)
# Perform Tukey's HSD test
tukey_test <- TukeyHSD(anova_result)
summary(tukey_test)
pvalues <- as.data.frame(tukey_test$met_pot)[,4] #padj


### Plots with significance labels 
sig_df <- data.frame(
  group1 = c("Low", "Low", "Moderate"),
  group2 = c("Moderate", "High", "High"),
  y.position = c(80, 88, 96),  # change these values as needed
  p.adj = pvalues
)

# convert p-values to star labels
sig_df$label <- ifelse(sig_df$p.adj < 0.001, "***", 
                  ifelse(sig_df$p.adj < 0.01, "**",
                  ifelse(sig_df$p.adj < 0.05, "*", "ns")))

p <- ggbarplot(centroid_sum_Winkler_SS2, x = "met_pot", y = "mean", 
          add = c("mean_sd", "jitter"),
          fill = "met_pot", 
          palette = c("#bfc4c6", "#6d7486", "#2b2d42"), 
          xlab = "Metastatic Potential",
          ylab = "Weighted Mean CD",
          ylim = c(0,100),
          position = position_dodge(0.8)) +
  stat_pvalue_manual(sig_df, label = "label", tip.length = 0.01, size = 3) +
  theme(legend.position = "none")
p


setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Winkler")
ggsave(filename = "WinklerSS2_CD_hist_sig.tiff", plot = p, width = 3, height = 2.5, dpi = 1200)




#### plot violin plot --------
# long format
names(centroid_distances) <- tumor_ID
centroid_distances_long <- do.call(rbind, lapply(names(centroid_distances), function(id) {
  data.frame(
    tumor_id = id,
    distance = centroid_distances[[id]],
    stringsAsFactors = FALSE
  )
})) %>%
  left_join(meta_data_table, by = "tumor_id")

# change anno
centroid_distances_long$met_pot <- gsub("low", "Low", centroid_distances_long$met_pot)
centroid_distances_long$met_pot <- gsub("intermediate", "Moderate", centroid_distances_long$met_pot)
centroid_distances_long$met_pot <- gsub("high", "High", centroid_distances_long$met_pot)

centroid_distances_long <- centroid_distances_long %>% mutate(met_pot = factor(met_pot, levels = c("Low", "Moderate", "High")))

centroid_distances_long$tumor_id <- factor(
  centroid_distances_long$tumor_id,
  levels = meta_data_table %>% arrange(desc(met_pot)) %>% pull(tumor_id)
)

#
p <- ggplot(centroid_distances_long, aes(x = tumor_id, y = distance, fill = tumor_id)) +
  geom_violin(trim = TRUE, scale = "width", alpha = 0.7, color = "black") + # Add black border to violins
  geom_jitter(width = 0.2, size = 0.001) +
  facet_wrap(~ met_pot, scales = "free_x", nrow = 1) + # Adjusted to facet_wrap for cleaner layout
  labs(
    title = "",
    x = "Metastatic Potential",
    y = "Weighted CD"
  ) +
   scale_fill_manual(values = custom_colors) +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    strip.text = element_text(size = 12, face = "bold"),
    strip.background = element_rect(fill = "white", color = "darkgrey"), # Add borders around facet labels
    panel.border = element_rect(color = "darkgrey", fill = NA, size = 2), # Add black borders around panels
    axis.text.x = element_blank(), # Larger x-axis text
    axis.text.y = element_text(size = 20), # Larger y-axis text
    axis.title.x = element_text(size = 24), # Larger x-axis title
    axis.title.y = element_text(size = 24), # Larger y-axis title
    legend.position = "right",
    legend.title = element_blank()
  )
p

setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Winkler")
ggsave(filename = "Winklerss2_CD_violin.tiff", width = 12, height = 6, dpi = 1200)

```

```{r SS2_T_vs_Met, fig.height=4, fig.width=6}

### Met ---------------
seu_ss2_met <- subset(seu_ss2, subset = sort == "Metastatic")

# get IDs
tumor_ID <- as.character(unique(seu_ss2_met@meta.data$Tumor_ID))
# Split by tumor_id
seu_ss2_met_split <- SplitObject(seu_ss2_met, split.by = "Tumor_ID")
# Filter the list, keeping only elements with 50 or more cells
seu_ss2_met_split <- seu_ss2_met_split[sapply(seu_ss2_met_split, function(x) ncol(x) >= 50)]
# update tumor_id
tumor_ID <- names(seu_ss2_met_split)


### Distance analysis
## get PCA coordinates
# initialize list to store df and SD for PCs
Winkler_PCs <- vector("list", length = length(tumor_ID)) # PCs
Winkler_PC_SD <- vector("list", length = length(tumor_ID)) # SD of PCs

# extract PCs and SDs per patient in for loop
for (i in 1:length(seu_ss2_met_split)) {
  # split patients
  tumor <- seu_ss2_met_split[[i]]
    # seurat pipeline
    tumor <- RunSeuratPipeline(tumor)
    # get PCs and SDs
    Winkler_PCs[[i]] <- GetPCs(tumor)
    Winkler_PC_SD[[i]] <- GetSDs(tumor, length(Winkler_PCs))
}
## calculate distance to centroid with SD correction
# calculate centroid
# initiate list
centroid_distances <- vector("list", length = length(Winkler_PCs))
#
for (i in 1:length(Winkler_PCs)) {
  centroid_distances[[i]] <- CalculateCentroidDistance(Winkler_PCs[[i]], withSD = TRUE, Winkler_PC_SD[[i]])
}

# summary
mean <- c()
sd <- c()

for (i in 1:length(centroid_distances)) {
  mean[i] <- mean(centroid_distances[[i]])
  sd[i] <- sd(centroid_distances[[i]])
}
#
centroid_sum_Winkler_SS2_met <- data.frame(mean = mean, 
                                       sd = sd, 
                                       tumor_id = tumor_ID,
                                       PCs = sapply(Winkler_PCs, ncol),
                                       weighted = c(rep("yes", times = length(centroid_distances))),
                                       group = c(rep("SS2", times = length(centroid_distances))),
                                       Tissue = c(rep("Met", times = length(centroid_distances))))

# add metastatic potential
meta_data_table <- as.data.frame(table(seu_ss2@meta.data$metastatic_potential_group, seu_ss2@meta.data$Tumor_ID))
colnames(meta_data_table) <- c("met_pot", "tumor_id", "count")
meta_data_table <- meta_data_table[meta_data_table$count > 0, ]
meta_data_table <- meta_data_table[meta_data_table$tumor_id %in% tumor_ID,]
centroid_sum_Winkler_SS2_met <- merge(centroid_sum_Winkler_SS2_met, meta_data_table[, c("met_pot", "tumor_id")], by = "tumor_id", all.x = TRUE)
    # change anno
    centroid_sum_Winkler_SS2_met$met_pot <- gsub("low", "Low", centroid_sum_Winkler_SS2_met$met_pot)
    centroid_sum_Winkler_SS2_met$met_pot <- gsub("intermediate", "Moderate", centroid_sum_Winkler_SS2_met$met_pot)
    centroid_sum_Winkler_SS2_met$met_pot <- gsub("high", "High", centroid_sum_Winkler_SS2_met$met_pot)

centroid_sum_Winkler_SS2_met <- centroid_sum_Winkler_SS2_met %>% mutate(met_pot = factor(met_pot, levels = c("Low", "Moderate", "High")))

# combine with PT
centroid_sum_Winkler_SS2_filtered <- centroid_sum_Winkler_SS2[centroid_sum_Winkler_SS2$tumor_id %in% centroid_sum_Winkler_SS2_met$tumor_id, ]
centroid_sum_Winkler_SS2_filtered <- centroid_sum_Winkler_SS2_filtered[, colnames(centroid_sum_Winkler_SS2_met)]
centroid_sum_Winkler_SS2_PTvsMet <- rbind(centroid_sum_Winkler_SS2_filtered, centroid_sum_Winkler_SS2_met)

centroid_sum_Winkler_SS2_PTvsMet$Tissue <- factor(centroid_sum_Winkler_SS2_PTvsMet$Tissue, levels = c("PT", "Met"))
centroid_sum_Winkler_SS2_PTvsMet$met_pot <- factor(centroid_sum_Winkler_SS2_PTvsMet$met_pot, levels = c("Low", "Moderate", "High"))

#setwd("D:/Dropbox/Master Thesis/Methods_transcript/Centroid_distance/Winkler")
#save(centroid_sum_Winkler_SS2_PTvsMet, file = "centroid_sum_Winkler_SS2_PTvsMet.RData")


p <- ggplot(centroid_sum_Winkler_SS2_PTvsMet, aes(x = Tissue, y = mean)) + 
  geom_bar(stat = "summary", fun = "mean", aes(fill = Tissue), width = 0.5, color = "black") +  # Single bar for Tumor and Met
  geom_errorbar(stat = "summary", fun.data = mean_se, width = 0.2) +  # Error bars for the means
  geom_point(aes(group = tumor_id), position = position_jitter(width = 0.01), size = 1, alpha = 1) +  # Individual points
  geom_line(aes(group = tumor_id, color = met_pot, linetype = met_pot), size = 0.5, alpha = 0.8) +  # Lines colored by met_pot
  scale_fill_manual(values = c("PT" = "goldenrod2", "Met" = "indianred2")) +  # Custom bar colors for Tumor and Met
  scale_color_manual(values = c("Low" = "#2b2d42", "Moderate" = "#2b2d42", "High" = "#2b2d42")) +  # Custom colors for met_pot
  scale_linetype_manual(values = c("Low" = "dotted", "Moderate" = "dashed", "High" = "solid")) +  # Different line type for Low
  theme_classic() +
theme(axis.text.x = element_text(size = 12, colour = "black"),
        axis.text.y = element_text(size = 12, colour = "black"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.position = "right") +
  labs(x = "Tissue", y = "Weighted Mean CD", color = "Metastatic\nPotential", linetype = "Metastatic\nPotential")

p

setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Winkler")
ggsave(filename = "Winklerss2_PTvsMet.tiff", width = 3.5, height = 2.5, dpi = 1200)



### Statistical test
# check normality
shapiro.test(centroid_sum_Winkler_SS2_PTvsMet$mean[centroid_sum_Winkler_SS2_PTvsMet$Tissue == "PT"])
shapiro.test(centroid_sum_Winkler_SS2_PTvsMet$mean[centroid_sum_Winkler_SS2_PTvsMet$Tissue == "Met"])

# Paired t-test
paired_data <- centroid_sum_Winkler_SS2_PTvsMet[centroid_sum_Winkler_SS2_PTvsMet$tumor_id %in% 
                                      centroid_sum_Winkler_SS2_PTvsMet$tumor_id[duplicated(centroid_sum_Winkler_SS2_PTvsMet$tumor_id)], ]

pt_values <- paired_data$mean[paired_data$Tissue == "PT"]
met_values <- paired_data$mean[paired_data$Tissue == "Met"]

# Perform paired t-test
ttest <- t.test(pt_values, met_values, paired = TRUE)
pvalues <- ttest$p.value

### Plots with significance labels 
sig_df <- data.frame(
      group1 = "PT",
      group2 = "Met",
      y.position = 85,  # change these values as needed
      p.adj = pvalues
)
    
    # convert p-values to star labels
    sig_df$label <- ifelse(sig_df$p.adj < 0.001, "***", 
                      ifelse(sig_df$p.adj < 0.01, "**",
                      ifelse(sig_df$p.adj < 0.05, "*", "ns")))
    
    
p <- ggplot(centroid_sum_Winkler_SS2_PTvsMet, aes(x = Tissue, y = mean)) + 
  geom_bar(stat = "summary", fun = "mean", aes(fill = Tissue), width = 0.5, color = "black") +  # Single bar for Tumor and Met
  geom_errorbar(stat = "summary", fun.data = mean_se, width = 0.2) +  # Error bars for the means
  geom_point(aes(group = tumor_id), position = position_jitter(width = 0.01), size = 1, alpha = 1) +  # Individual points
  geom_line(aes(group = tumor_id, color = met_pot, linetype = met_pot), size = 0.5, alpha = 0.8) +  # Lines colored by met_pot
  scale_fill_manual(values = c("PT" = "goldenrod2", "Met" = "indianred2")) +  # Custom bar colors for Tumor and Met
  scale_color_manual(values = c("Low" = "#2b2d42", "Moderate" = "#2b2d42", "High" = "#2b2d42")) +  # Custom colors for met_pot
  scale_linetype_manual(values = c("Low" = "dotted", "Moderate" = "dashed", "High" = "solid")) +  # Different line type for Low
  theme_classic() +
  ylim(0,90) +
  stat_pvalue_manual(sig_df, label = "label", tip.length = 0.01) +
theme(axis.text.x = element_text(size = 12, colour = "black"),
        axis.text.y = element_text(size = 12, colour = "black"),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        legend.position = "right") +
  labs(x = "Tissue", y = "Weighted Mean CD", color = "Metastatic\nPotential", linetype = "Metastatic\nPotential")

p

setwd("D:/Dropbox/Master Thesis/Thesis/Figures/Winkler/SmartSeq2")
ggsave(filename = "Winklerss2_PTvsMet_sig.tiff", width = 3.5, height = 2.5, dpi = 1200)
    
```
